package com.apon.taalmaatjes.frontend.transition;

public enum ScreenEnum {
    STUDENTS_OVERVIEW, STUDENTS_DETAIL, STUDENTS_ADD,
    VOLUNTEERS_OVERVIEW, VOLUNTEERS_DETAIL, VOLUNTEERS_ADD, VOLUNTEERS_ADD_MATCH, VOLUNTEERS_ADD_INSTANCE,
    VOLUNTEERS_EDIT_LOG,
    TASKS_OVERVIEW, TASKS_DETAIL, TASKS_ADD,
    REPORT
}
