package com.apon.taalmaatjes.frontend.transition;

public enum ScreenEnum {
    HOME,
    STUDENTS_OVERVIEW, STUDENTS_DETAIL, STUDENTS_ADD,
    VOLUNTEERS_OVERVIEW, VOLUNTEERS_DETAIL, VOLUNTEERS_ADD, VOLUNTEERS_ADD_MATCH,
    REPORT
}
